default: &default
  adapter: sqlite3
  encoding: utf8
  pool: 5
  user: user
  staff: staff

development:
  <<: *default
  database: grape_bootstrap_development

test:
  <<: *default
  database: grape_bootstrap_development

